#!/usr/bin/env python3
"""fetch-fonts.py — download the web UI's self-hosted fonts (all SIL OFL 1.1).

Latin/Cyrillic families come from the Google Fonts CSS2 API as unicode-range
subsets, so browsers fetch only the slices a page actually uses.

CJK display serifs (Noto Serif SC/TC/JP/KR) would be megabytes each, so they
are subset server-side (`text=`) to exactly the characters used by display
strings — i18n keys whose last segment starts with "title" or ends with
"Title" — in web/assets/i18n/<locale>.json. Body text uses system CJK fonts.

Re-run after changing any CJK title string:

    python3 scripts/fetch-fonts.py          # CJK subsets + missing Latin files
    python3 scripts/fetch-fonts.py --force  # re-download everything

Only this script talks to Google; at runtime the fonts are served from the
embedded web/ directory, so the UI has no third-party requests.
"""
import hashlib
import json
import pathlib
import re
import sys
import urllib.parse
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "web" / "assets" / "fonts"
I18N = ROOT / "web" / "assets" / "i18n"
API = "https://fonts.googleapis.com/css2?"
LICENSE_BASE = "https://raw.githubusercontent.com/google/fonts/main/"
# A modern UA makes the API answer with variable woff2 + unicode-range slices.
UA = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36")

# (CSS family, file slug, CSS2 family spec, subsets to keep, license dir)
LATIN = [
    ("Fraunces", "fraunces",
     "Fraunces:ital,opsz,wght,SOFT,WONK@0,9..144,300..700,0..100,0;1,9..144,300..700,0..100,0",
     ["latin", "latin-ext"], "ofl/fraunces"),
    ("Inter", "inter", "Inter:wght@300..700",
     ["latin", "latin-ext", "cyrillic", "cyrillic-ext", "greek"], "ofl/inter"),
    ("JetBrains Mono", "jetbrains-mono", "JetBrains Mono:wght@400..700",
     ["latin", "latin-ext", "cyrillic"], "ofl/jetbrainsmono"),
    # Fraunces has no Cyrillic; Lora supplies Russian display glyphs only.
    ("Lora", "lora", "Lora:ital,wght@0,400..700;1,400..700",
     ["cyrillic", "cyrillic-ext"], "ofl/lora"),
]

# (CSS family, file slug, Google family, weight, locale)
CJK = [
    ("MB Serif SC", "serif-sc", "Noto Serif SC", 600, "zh-CN"),
    ("MB Serif TC", "serif-tc", "Noto Serif TC", 600, "zh-TW"),
    ("MB Serif JP", "serif-jp", "Noto Serif JP", 600, "ja"),
    ("MB Serif KR", "serif-kr", "Noto Serif KR", 600, "ko"),
]
CJK_LICENSE = "ofl/notoserifsc"

DISPLAY_KEY = re.compile(r"(^title|Title$)")


def get(url):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as r:
        return r.read()


def css_blocks(css):
    """Yield (subset-or-None, {descriptor: value}) for each @font-face."""
    for m in re.finditer(r"(?:/\*\s*([\w-]+)\s*\*/\s*)?@font-face\s*\{(.*?)\}", css, re.S):
        desc = {}
        for part in m.group(2).split(";"):
            if ":" in part:
                k, v = part.split(":", 1)
                desc[k.strip()] = v.strip()
        yield m.group(1), desc


def face(family, style, weight, file, urange=None):
    rules = [f'font-family:"{family}"', f"font-style:{style}", f"font-weight:{weight}",
             "font-display:swap", f'src:url({file}) format("woff2")']
    if urange:
        rules.append(f"unicode-range:{urange}")
    return "@font-face{" + ";".join(rules) + "}"


def flatten(d, prefix=""):
    for k, v in d.items():
        key = f"{prefix}.{k}" if prefix else k
        if isinstance(v, dict) and "other" not in v:
            yield from flatten(v, key)
        elif isinstance(v, dict):
            for form in v.values():
                yield key, form
        else:
            yield key, v


def display_chars(locale):
    path = I18N / f"{locale}.json"
    if not path.exists():
        return ""
    chars = set()
    for key, text in flatten(json.loads(path.read_text("utf-8"))):
        if DISPLAY_KEY.search(key.rsplit(".", 1)[-1]):
            # ASCII and General Punctuation are covered by Fraunces.
            chars.update(c for c in text if ord(c) > 0x2E7F)
    return "".join(sorted(chars))


def ranges(chars):
    cps = sorted(ord(c) for c in chars)
    out, start, prev = [], None, None
    for cp in cps + [None]:
        if start is None:
            start = prev = cp
        elif cp is not None and cp == prev + 1:
            prev = cp
        else:
            out.append(f"U+{start:X}" if start == prev else f"U+{start:X}-{prev:X}")
            start = prev = cp
    return ",".join(out)


def main():
    force = "--force" in sys.argv
    OUT.mkdir(parents=True, exist_ok=True)
    css = ["/* Generated by scripts/fetch-fonts.py. Do not edit by hand. */"]
    total = 0

    for family, slug, spec, subsets, lic in LATIN:
        sheet = get(API + "family=" + urllib.parse.quote(spec, safe=":,.@;") + "&display=swap").decode()
        for subset, d in css_blocks(sheet):
            if subset not in subsets:
                continue
            style = d["font-style"]
            file = f"{slug}-{style}-{subset}.woff2"
            dest = OUT / file
            if force or not dest.exists():
                url = re.search(r"url\(([^)]+)\)", d["src"]).group(1)
                dest.write_bytes(get(url))
            total += dest.stat().st_size
            css.append(face(family, style, d["font-weight"], file, d.get("unicode-range")))
        lic_file = OUT / f"{slug}-OFL.txt"
        if force or not lic_file.exists():
            lic_file.write_bytes(get(LICENSE_BASE + lic + "/OFL.txt"))

    for family, slug, gfamily, weight, locale in CJK:
        text = display_chars(locale)
        if not text:
            print(f"skip {family}: no display strings in {locale}.json", file=sys.stderr)
            continue
        spec = f"{gfamily}:wght@{weight}"
        sheet = get(API + "family=" + urllib.parse.quote(spec, safe=":,.@;")
                    + "&text=" + urllib.parse.quote(text) + "&display=swap").decode()
        _, d = next(css_blocks(sheet))
        url = re.search(r"url\(([^)]+)\)", d["src"]).group(1)
        data = get(url)
        # Content-hashed name: the server caches fonts for a year (immutable),
        # and this subset changes whenever a title string does.
        file = f"{slug}-{weight}-{hashlib.sha256(data).hexdigest()[:8]}.woff2"
        for old in OUT.glob(f"{slug}-{weight}*.woff2"):
            old.unlink()
        (OUT / file).write_bytes(data)
        total += len(data)
        # unicode-range keeps the file from loading on pages without CJK titles.
        css.append(face(family, "normal", str(weight), file, ranges(text)))
        print(f"{family}: {len(text)} glyphs, {(OUT / file).stat().st_size // 1024} KiB")
    lic_file = OUT / "noto-serif-cjk-OFL.txt"
    if force or not lic_file.exists():
        lic_file.write_bytes(get(LICENSE_BASE + CJK_LICENSE + "/OFL.txt"))

    (OUT / "fonts.css").write_text("\n".join(css) + "\n", "utf-8")
    print(f"wrote {OUT / 'fonts.css'} — {total // 1024} KiB of woff2")


if __name__ == "__main__":
    main()
